### ISSUE TITLE
Bump TurboVNC and NoVNC to support Unicode in clipboard

### ISSUE THREAD

**Issue by sjtuross** [ich777/docker-novnc-baseimage#1] opened 2022-08-01 07:09 UTC
With TurboVNC 2.2.6 and NoVNC 1.2.0 used in the base image, clipboard doesn't support Unicode well. In the below screenshot, if I select some Chinese characters within Ungoogled-Chromium container, Unicode is encoded to ISO8859-1 and shown in NoVNC clipboard (if I copy paste this text to an ISO8859-1 encoded text file and then convert it to UTF-8 encoding in Notepad++, I can get the correct Chinese characters).

![image](https://user-images.githubusercontent.com/940110/182089466-531dc5cb-2cc6-4362-95cb-8f5ebf29fcce.png)

Per this issue https://github.com/TurboVNC/turbovnc/issues/113, It seems TurboVNC will support Unicode in the upcoming 3.1 version.

In the meanwhile, I tested this image https://hub.docker.com/r/accetto/ubuntu-vnc-xfce-chromium-g3. Per it's [changelog](https://github.com/accetto/ubuntu-vnc-xfce-g3/blob/master/CHANGELOG.md), it uses TigerVNC 1.12.0 and noVNC 1.3.0. Clipboard can perfectly support Unicode.

This issue currently exists in all your great images as all are derived from this base image. Hopefully also bump NoVNC to 1.3.0.

Thanks a lot!

**Comment by ich777** [comment] 2022-08-01 08:02
@sjtuross thank you for the message.
Please keep me updated when TurboVNC 3.1 is released and I will push a update to this container and all containers.

**Comment by ich777** [comment] 2022-08-03 06:37
@sjtuross may I ask a favor from you?
If you got a little bit of spare time, can you test the `beta` branch from the Ungoogled-Chromium container by simply changing the tag from `ich777/ungoogled-chromium` to `ich777/ungoogled-chromium:beta` and please report back if it fixes your issue?

**Comment by sjtuross** [comment] 2022-08-03 13:28
@ich777 Thank you for working on this. I tried the beta build. Unfortunately NoVNC 1.3.0 + TurboVNC 3.0 still have the same issue. I think the issue comes from TurboVNC only and it's supposed to have been fixed in the 3.1 evolving pre-release build https://s3.amazonaws.com/turbovnc-pr/dev/linux/index.html.

**Comment by ich777** [comment] 2022-08-04 06:27
@sjtuross Yes, this issue is indeed caused by TurboVNC itself.
I will keep an eye on that but keep me updated if I miss the update from TurboVNC.

As for the pre-release, I can of course build a container with that version but that won't make it in the stable version from my container. If you are interested I will look into this in the next few days.

**Comment by sjtuross** [comment] 2022-08-04 09:31
@ich777 Totally understand you won't bring the pre-release TurboVNC to the stable version. That's why I originally requested to replace it with TigerVNC 1.12 which is stable and working, but I understand you might have reasons to stick to TurboVNC. If that's the case, I'm still interested in trying the pre-release in the beta branch, so I can have a working Unicode clipboard to interact with the outside without having to wait months for 3.1. Thanks again!

**Comment by ich777** [comment] 2022-08-05 10:38
@sjtuross development build now available: `ich777/ungoogled-chromium:dev` and looking good:
![image](https://user-images.githubusercontent.com/28066518/183060104-2da1378e-1a6d-40ad-b353-5cb66b058b83.png)

Maybe you can convince the developers from TurboVNC that they can release a minor or patch release with this fix included and I will update all my TurboVNC containers.

**Comment by sjtuross** [comment] 2022-08-05 14:00
@ich777 Although it's expected to work but still feel like magic. I just left a comment there for a patch release. Hopefully it will be considered. I think browser needs more interaction with the outside than the other tools, For now, ich777/ungoogled-chromium:dev works perfectly for me.

**Comment by ich777** [comment] 2022-08-05 15:07
@sjtuross glad that it is working now for you! :)
Please keep me updated if I miss the release, currently missing a few things because real life...

**Comment by Jing0807** [comment] 2023-09-01 02:16
嘿！！你们两个，我想说，超牛逼的！！！感谢你们为此付出的一切！！

**Comment by ich777** [comment] 2024-01-26 11:32
@sjtuross & @Jing0807 the container (and hopefully all my containers that rely on that base image) are now updated to TurboVNC 3.1

**Comment by ich777** [comment] 2024-01-28 15:47
I‘ll close this issue for now, if you have any further questions feel free to reopen this issue or create a new issue.

**Closed as completed by ich777** 2024-01-28 15:47 UTC
